---
title: "eda_slay"
author: "Richa"
date: "2024-04-29"
output: html_document
---


```{r, message = F}
rm(list = ls())

library(caret)
library(tidyverse)
library(dplyr)
library(readr)
library(randomForest)
library(janitor)
library(xgboost)
library(glmnet)
```

```{r}
# read in train and test data
admissions_test <- readRDS("admissions_test.rdata") %>% select(-c(1:4, 9, 57, 58))
admissions_train <- readRDS("admissions_train.rdata") %>% select(-c(1:4, 9, 57, 58))
```

```{r}
full <- rbind(admissions_train, admissions_test)

dfs <- list(full, admissions_train, admissions_test)
endlist <- list()

for(i in seq_along(dfs)) {
  test <- summarise_if(dfs[[i]], function(x) class(x)[1]  == "numeric", list(Mean.Count = mean, SD.Prop = sd)) %>%
    pivot_longer(cols = everything()) %>%
    separate(name, into = c("var", "Func"), sep = "_(?=[^_]*$)") %>%
    pivot_wider(names_from = var, values_from = value)
  testBin <- summarise_if(dfs[[i]], is.integer, list(Mean.Count = sum, SD.Prop = mean)) %>%
    pivot_longer(cols = everything()) %>%
    separate(name, into = c("var", "Func"), sep = "_(?=[^_]*$)") %>%
    pivot_wider(names_from = var, values_from = value)
  factorvars <- colnames(dfs[[i]] %>% select(where(is.factor) | where(is.character)))
  summary_func <- function(var){
    var = enquo(var)
    out = dfs[[i]] %>% mutate(total = n()) %>% group_by(!!var) %>% summarize(Mean.Count = n(), SD.Prop = Mean.Count/first(total))
    return(out)
  }
  testCat <- lapply(factorvars, summary_func)
  test_fin <- left_join(test, testBin, by = "Func")
  endlist[[i]] <- test_fin
}

final <- bind_rows(endlist, .id = "Dataframe") %>%
  mutate(Dataframe = c(rep("Full", 2), rep("Training", 2), rep("Test", 2)))
final <- final %>%
  t() %>%
  as.data.frame()

```

```{r}
factorvars <- colnames(dfs[[1]] %>% select(where(is.factor) | where(is.character)))
summary_func <- function(data, var){
    var = enquo(var)
    out = data %>% 
      mutate(total = n()) %>%
      group_by(!!var) %>% 
      summarize(Mean.Count = n(), 
                SD.Prop = Mean.Count/first(total))
    return(out)
}

summary_func(admissions_test, GENDER)
```

```{r}
dfs[[1]] %>%
  select(factorvars) %>%
  pivot_longer(everything(), names_to="variables", values_to = "values") %>%
  group_by(variables, values) %>%
  summarize(Mean.Count = n(), SD.Prop = Mean.Count/nrow(dfs[[1]]))

```

