---
title: "table1_slay"
date: "2024-04-29"
output: html_document
---

# Library Loading

```{r, message = F}
rm(list = ls())

library(caret)
library(tidyverse)
library(dplyr)
library(readr)
library(randomForest)
library(janitor)
library(xgboost)
library(glmnet)
library(writexl)
```

# Data Import and Binding

```{r, message = F}
import_clean <- function(file){
  readRDS(file) %>% select(-c(1:4, 9, 57, 58)) %>% clean_names() %>% 
    mutate(male = ifelse(gender == "M", 1, 0),
           urban = ifelse(rural == "U", 1, 0),
           emergency_admission = ifelse(type_of_admission_emergency_opd == "E", 1, 0),
           across(c(age, duration_of_stay, duration_of_intensive_unit_stay), ~ as.numeric(.)),
           across(c(chest_infection, readmission, male, urban, emergency_admission), ~ as.integer(.))) %>% 
    select(-c(gender, rural, type_of_admission_emergency_opd))
}

admissions_test <- import_clean("admissions_test.rdata")
admissions_train <- import_clean("admissions_train.rdata")
full <- rbind(admissions_train, admissions_test)

dfs <- list(full, admissions_train, admissions_test)
```

# Generating Table 1 Output

```{r}
endlist <- list()
for(i in seq_along(dfs)) {
  test <- summarise_if(dfs[[i]], function(x) class(x)[1]  == "numeric", list(Mean.Count = mean, SD.Prop = sd)) %>%
    pivot_longer(cols = everything()) %>%
    separate(name, into = c("var", "Func"), sep = "_(?=[^_]*$)") %>%
    pivot_wider(names_from = var, values_from = value)
  testBin <- summarise_if(dfs[[i]], is.integer, list(Mean.Count = sum, SD.Prop = mean)) %>%
    pivot_longer(cols = everything()) %>%
    separate(name, into = c("var", "Func"), sep = "_(?=[^_]*$)") %>%
    pivot_wider(names_from = var, values_from = value)
  testCat <- dfs[[i]] %>% mutate(total = n()) %>% group_by(outcome) %>% 
    summarize(Mean.Count = n(), SD.Prop = Mean.Count/first(total)) %>% 
    pivot_longer(cols = c(2:3), names_to = "Func") %>% pivot_wider(names_from = outcome)
  test_fin <- left_join(test, testBin, by = "Func") %>% left_join(testCat, by = "Func")
  endlist[[i]] <- test_fin
}

combined <- bind_rows(endlist, .id = "Dataframe") %>%
  mutate(Dataframe = c(rep("Full", 2), rep("Training", 2), rep("Test", 2)))
final <- combined %>% 
  pivot_longer(cols = c(3:ncol(combined))) %>% 
  pivot_wider(names_from = c(Dataframe, Func))
```

# Export Table 1 Excel for Proper Formatting

```{r}
# write_xlsx(final, "Table 1 Data.xlsx")
```


